In [15]:
import numpy as np
import pandas as pd

In [16]:
df = pd.read_csv("shopping_behavior_updated.csv")
print(df.shape)

drop_cols = ["Customer ID"]
df = df.drop(columns=drop_cols)
df.head(-20)

(3900, 18)

,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3875,63,Female,Hat,Accessories,51,New Hampshire,M,Pink,Winter,3.3,No,2-Day Shipping,No,No,21,Credit Card,Annually
3876,60,Female,Shoes,Footwear,85,Wisconsin,S,Cyan,Fall,2.6,No,2-Day Shipping,No,No,7,Cash,Annually
3877,28,Female,Hoodie,Clothing,96,Nevada,M,Olive,Spring,4.2,No,Next Day Air,No,No,46,Debit Card,Monthly
3878,60,Female,Hat,Accessories,42,South Carolina,M,Pink,Summer,3.4,No,2-Day Shipping,No,No,24,Credit Card,Annually
3879,26,Female,Skirt,Clothing,63,Florida,L,Maroon,Winter,4.1,No,Free Shipping,No,No,6,Debit Card,Quarterly

In [17]:
for col in ['Gender', 'Item Purchased', 'Category', 'Location', 'Size', 'Color', 'Season', 'Subscription Status', 'Shipping Type', 'Discount Applied', 'Promo Code Used', 'Payment Method', 'Frequency of Purchases']:
    codes, unique = pd.factorize(df[col])
    df[col] = codes

# payment_method = df.pop("Gender")
# df["Gender"] = payment_method
df.head()

,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,55,0,0,0,53,0,0,0,0,3.1,0,0,0,0,14,0,0
1,19,0,1,0,64,1,0,1,0,3.1,0,0,0,0,2,1,0
2,50,0,2,0,73,2,1,1,1,3.1,0,1,0,0,23,2,1
3,21,0,3,1,90,3,2,1,1,3.5,0,2,0,0,49,3,1
4,45,0,0,0,49,4,2,2,1,2.7,0,1,0,0,31,3,2

In [18]:
df.to_csv("shopping_processed.csv", header=False, index=False)